- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "/home/ubuntu/app/{{ item.dest }}"
  loop:
    - src: "docker-compose.app.yml"
      dest: "docker-compose.app.yml"
    - src: "nginx"
      dest: "."
    - src: "renew-cert.sh"
      dest: "renew-cert.sh"

- name: Create .env for docker-compose to load
  copy:
    dest: "/home/ubuntu/app/.env"
    content: |
      export COMPOSE_FILE=docker-compose.app.yml
      export APP_SERVER_NAME="{{ APP_SERVER_NAME }}"
    mode: 0644

- name: Request LetsEncrypt SSL Cert
  script:
    cmd: "init-certbot.sh"
  become: yes
  become_user: ubuntu
  args:
    chdir: "/home/ubuntu/app"

- name: Start Docker Containers
  command: docker-compose up -d
  become: yes
  args:
    chdir: "/home/ubuntu/app"

- name: Add a cron job to run a script daily at 12AM
  cron:
    name: "Certbot renewal"
    minute: "0"
    hour: "0"
    job: "/home/ubuntu/app/renew-cert.sh"
    state: present
