name: Deploy monitoring stack with ansible
on:
  workflow_run:
    workflows: [Terraform Apply]
    types: [completed]
    branches: [infra_main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR branch
        uses: actions/checkout@v4

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Decode and Save PEM File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2-key.pem
          chmod 400 ec2-key.pem
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download Terraform Output
        uses: actions/download-artifact@v4
        with:
          name: terraform-output
          path: ./output
      - name: Run ansible playbook
        run: |
          instance_id=$(cat ./output/instance_id.txt)
          public_ip=$(cat ./output/public_ip.txt)
          echo "Instance ID: $instance_id"
          echo "Public IP: $public_ip"
          printf "[web_servers]\n$public_ip ansible_user=ubuntu ansible_ssh_private_key_file=ec2-key.pem" > inventory.ini
          aws ec2 wait instance-status-ok --instance-ids $instance_id 
          ansible-playbook -i inventory.ini ansible/deploy_monitoring_stack.yml
