name: Terraform Apply

on:
  push:
    branches:
      - infra_main

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_ami: ${{ secrets.TF_VAR_ami }}
      TF_VAR_security_group_ids: ${{ secrets.TF_VAR_security_group_ids }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
      TF_VAR_eip: ${{ secrets.TF_VAR_eip }}
      TF_VAR_domain_name: ${{ secrets.TF_VAR_domain_name }}
      TF_VAR_ec2_key_path: $GITHUB_WORKSPACE/ec2-key.pem

    steps:
      - name: checkout PR branch
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Decode and Save PEM File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve
