name: Terraform Apply

on:
  push:
    branches:
      - infra_main

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_ami: ${{ secrets.TF_VAR_ami }}
      TF_VAR_security_group_ids: ${{ secrets.TF_VAR_security_group_ids }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
      TF_VAR_eip: ${{ secrets.TF_VAR_eip }}

    steps:
      - name: checkout PR branch
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve

      - name: terraform output
        run: |
          terraform output instance_id > instance_id.txt
          terraform output public_ip > public_ip.txt

      - name: Upload Terraform Output
        uses: actions/upload-artifact@v3
        with:
          name: terraform-output
          path: |
            instance_id.txt
            public_ip.txt
